#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
wired &
#$HOME/.config/polybar/launch.sh
picom -c --corner-radius 8 &

lightmode

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config active_border_color "#ffffff"
bspc config normal_border_color "#ffffff"
bspc config focused_border_color "#ffffff"

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty state=floating center=true rectangle=800x450+0+0

